language: php
sudo: false

php:
  - "7.1"
  - "7.2"
  - "7.3"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist --no-interaction

script:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/phpunit --coverage-clover build/logs/clover.xml; else vendor/bin/phpunit; fi
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then vendor/bin/php-cs-fixer fix --config=vendor/ixocreate/coding-standard/.php_cs -v --dry-run --using-cache=no --path-mode=intersection `git diff --name-only --diff-filter=ACMRTUXB $TRAVIS_COMMIT_RANGE`; fi

after_success:
  - if [ $TRAVIS_PHP_VERSION = '7.2' ]; then php vendor/bin/php-coveralls -v; fi

notifications:
  email: false
  slack:
    secure: "Ys3MGDxJN+kxCJHnYgN+apEkJpWcNlNxqeGvL+Xgp2/4iTAtyTTMF9HyJ3P1b/LAclen0hzZGdsKwdXSw4I1crQPOaFimf/UmzzkPlUsPv9PhBhYerLiEVuZ+4naXo910T/nD4PoebllEUUb2hdebu5GBzk3fWn+HTEG10c3YegjaV4v2XUXg2l7nnsr2qx1KUTQs+9Qs7c52wDd0OkfAdxSQSpzi1B5iLjaC+SAHGkaoxXQrSuouv8r0V7T37HxXtvqBMzGL7nA8w26eiLUaHFPbnRPcIYKMZKPuyrCx41Ne8f8kJy1o4+46PX3GpHJuEt/ufchD2wj6LekRtVQRn99rf1SkRF3hdV8b+JYJxPLwfU80WJaBNLurjt7wA07QiQCDLendjzyt0ZIHEZlBLosN5yjJfHz9bz/Q9Ve50QXdAA21rPiVb0bRZKlHUdObeV9ycr5SmnH0YjREHO6OKePDq/F+Dxslhe6fcJfqVA68ytd2g528hGPC+9XkwQJxWSnmjOTmE+FYZhq8HDkdlGblP0OZHJnGgpz50Xk5Y4YZLvFAYyrZ0A7HQNkXduuyqVCiAJTty8i6nsBWWTz5KONH8PTap+YqpQFbek4z+fPA0dFLUzjGYsKMqtZtpGY9yddZwcD8mi6FZ+meIO5MCXlfv5n1kafN3eplHbOOYQ="
    on_success: change # default: always
    on_failure: change # default: always
